# 单体部署
version: '3.7'
services:
  database:
    image: mongo:bionic
    restart: always
    volumes:
      - ~/data/db/gcp:/data/db
    ports:
      - 27017:27017
    networks:
      - gcp-web-net
  web:
    build: .
    image: gcp
    environment:
      - NODE_ENV=prod
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/gcp/auth/auth.json
    depends_on:
      - database
    volumes:
      - /data/logs/gcp:/usr/src/gcp/logs
      - /var/projects/gcp/auth:/usr/src/gcp/auth
      - /var/projects/gcp/bash:/var/local/mysh
    ports:
      - 5050:5050
    networks:
      - gcp-web-net
networks:
  gcp-web-net:
    driver: bridge
